<?php return array (
  'mall.index' => 
  array (
    'url' => 'mall.index',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'mall.type_module_two,slider.show_15,diymodule.show_114,mall.goods_module(id:0|tag:|width:100%|height:715px|sequence_field:sequence|sequence_type:desc|quantity:10|show_method:show_grid|target:_self|pc_buy_button:0|phone_buy_button:1|title:<SPAN>1F</span>商品1|show_sub:4|img:2015_02/11/1423646038_0_7253*jpg|img_link:|img_width:276px|follow_type:true|follow_page:true),diymodule.show_115,,diymodule.show_116,,diymodule.show_117,,diymodule.show_117,,',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'mall.shop_index' => 
  array (
    'url' => 'mall.shop_index',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_122,mall.shop_name,mall.shop_search,mall.cart,,mall.layout',
    'left' => '',
    'right' => '',
    'full' => '',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'mall.shop_list' => 
  array (
    'url' => 'mall.shop_list',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => 'mall.shop_list',
    'full' => 'mall.shop_list',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'mall.shop_goods_type' => 
  array (
    'url' => 'mall.shop_goods_type',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'mall.shop_goods_type',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'mall.shop_goods_list' => 
  array (
    'url' => 'mall.shop_goods_list',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_122,mall.shop_name,mall.shop_search,mall.cart,mall.layout',
    'left' => '',
    'right' => '',
    'full' => '',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'mall.apply_shop' => 
  array (
    'url' => 'mall.apply_shop',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'mall.apply_shop',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'mall.shop_diypage' => 
  array (
    'url' => 'mall.shop_diypage',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'mall.shop_diypage',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'mall.show_type' => 
  array (
    'url' => 'mall.show_type',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,mall.search,mall.cart,index.navigation,index.customer_service',
    'left' => '',
    'right' => '',
    'full' => 'mall.show_type',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'mall.goods_list' => 
  array (
    'url' => 'mall.goods_list',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => ',mall.show_type_module(id:0|title:diy_name|show_deep:3|width:100%|height:auto|target:_self|follow_type:true)',
    'right' => 'mall.goods_list',
    'full' => 'mall.goods_list,mall.interest_goods',
    'bottom' => 'index.foot,index.device,,diymodule.show_145,diymodule.show_148',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'mall.goods' => 
  array (
    'url' => 'mall.goods',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_122,mall.shop_name,mall.shop_search,mall.cart,,mall.layout',
    'left' => '',
    'right' => '',
    'full' => '',
    'bottom' => ',diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
    'not_cache' => '1',
  ),
  'mall.package' => 
  array (
    'url' => 'mall.package',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'mall.package',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'mall.master' => 
  array (
    'url' => 'mall.master',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.master',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.shop_admin' => 
  array (
    'url' => 'mall.shop_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.shop_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.shop_edit' => 
  array (
    'url' => 'mall.shop_edit',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.shop_edit',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.color' => 
  array (
    'url' => 'mall.color',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.color',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.m_order_admin' => 
  array (
    'url' => 'mall.m_order_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.m_order_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.m_comment_admin' => 
  array (
    'url' => 'mall.m_comment_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.m_comment_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.m_goods_admin' => 
  array (
    'url' => 'mall.m_goods_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => 'mall.m_goods_admin',
    'right' => '',
    'full' => 'mall.m_goods_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.type' => 
  array (
    'url' => 'mall.type',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.type',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.type_remark' => 
  array (
    'url' => 'mall.type_remark',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.type_remark',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.type_attribute' => 
  array (
    'url' => 'mall.type_attribute',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.type_attribute',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.type_brand' => 
  array (
    'url' => 'mall.type_brand',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.type_brand',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.type_option' => 
  array (
    'url' => 'mall.type_option',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.type_option',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.type_price' => 
  array (
    'url' => 'mall.type_price',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.type_price',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.tag' => 
  array (
    'url' => 'mall.tag',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.tag',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.unit' => 
  array (
    'url' => 'mall.unit',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.unit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.show_type_module_set' => 
  array (
    'url' => 'mall.show_type_module_set',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.show_type_module_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.goods_module_set' => 
  array (
    'url' => 'mall.goods_module_set',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.goods_module_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.pay_method' => 
  array (
    'url' => 'mall.pay_method',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.pay_method',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.invoice' => 
  array (
    'url' => 'mall.invoice',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.invoice',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.config' => 
  array (
    'url' => 'mall.config',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.config',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.goods_set' => 
  array (
    'url' => 'mall.goods_set',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.goods_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.s_search_log' => 
  array (
    'url' => 'mall.s_search_log',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.s_search_log',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.m_order_detail' => 
  array (
    'url' => 'mall.m_order_detail',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.m_order_detail',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.express' => 
  array (
    'url' => 'mall.express',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.express',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.seller' => 
  array (
    'url' => 'mall.seller',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.seller',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.shop_set' => 
  array (
    'url' => 'mall.shop_set',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.shop_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.shop_config' => 
  array (
    'url' => 'mall.shop_config',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.shop_config',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.shop_head' => 
  array (
    'url' => 'mall.shop_head',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.shop_head',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.navigation' => 
  array (
    'url' => 'mall.navigation',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.navigation',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.member_set' => 
  array (
    'url' => 'mall.member_set',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.member_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.shop_goods_type_module_set' => 
  array (
    'url' => 'mall.shop_goods_type_module_set',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.shop_goods_type_module_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.shop_goods_list_module_set' => 
  array (
    'url' => 'mall.shop_goods_list_module_set',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.shop_goods_list_module_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.diymodule_admin' => 
  array (
    'url' => 'mall.diymodule_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.diymodule_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.diymodule_edit' => 
  array (
    'url' => 'mall.diymodule_edit',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.diymodule_edit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.relevance_goods' => 
  array (
    'url' => 'mall.relevance_goods',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.relevance_goods',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.relevance_package' => 
  array (
    'url' => 'mall.relevance_package',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.relevance_package',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.order_admin' => 
  array (
    'url' => 'mall.order_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.order_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.comment_admin' => 
  array (
    'url' => 'mall.comment_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.comment_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.comment_answer' => 
  array (
    'url' => 'mall.comment_answer',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.comment_answer',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.goods_admin' => 
  array (
    'url' => 'mall.goods_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.goods_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.goods_add' => 
  array (
    'url' => 'mall.goods_add',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.goods_add',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.goods_edit' => 
  array (
    'url' => 'mall.goods_edit',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.goods_edit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.package_admin' => 
  array (
    'url' => 'mall.package_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.package_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.position' => 
  array (
    'url' => 'mall.position',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.position',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.supplier' => 
  array (
    'url' => 'mall.supplier',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.supplier',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.free_shipping' => 
  array (
    'url' => 'mall.free_shipping',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.free_shipping',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.express_price' => 
  array (
    'url' => 'mall.express_price',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.express_price',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.coupon_code' => 
  array (
    'url' => 'mall.coupon_code',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.coupon_code',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.discount' => 
  array (
    'url' => 'mall.discount',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.discount',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.fulfil_preferential' => 
  array (
    'url' => 'mall.fulfil_preferential',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.fulfil_preferential',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.vouchers' => 
  array (
    'url' => 'mall.vouchers',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.vouchers',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.goods_add_option_type' => 
  array (
    'url' => 'mall.goods_add_option_type',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.goods_add_option_type',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.s_type' => 
  array (
    'url' => 'mall.s_type',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.s_type',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.s_type_remark' => 
  array (
    'url' => 'mall.s_type_remark',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.s_type_remark',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.goods_quantity_log' => 
  array (
    'url' => 'mall.goods_quantity_log',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.goods_quantity_log',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.goods_batch' => 
  array (
    'url' => 'mall.goods_batch',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.goods_batch',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.search_log' => 
  array (
    'url' => 'mall.search_log',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.search_log',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.order_edit' => 
  array (
    'url' => 'mall.order_edit',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.order_edit',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.order_print' => 
  array (
    'url' => 'mall.order_print',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.order_print',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'mall.tag_print' => 
  array (
    'url' => 'mall.tag_print',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.tag_print',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'mall.order_detail' => 
  array (
    'url' => 'mall.order_detail',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.order_detail',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.s_tag' => 
  array (
    'url' => 'mall.s_tag',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.s_tag',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.buyer' => 
  array (
    'url' => 'mall.buyer',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'mall.buyer',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.my_order' => 
  array (
    'url' => 'mall.my_order',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.my_order',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.my_cart' => 
  array (
    'url' => 'mall.my_cart',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'mall.my_cart',
    'bottom' => 'index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
    'not_cache' => '1',
  ),
  'mall.confirm_order' => 
  array (
    'url' => 'mall.confirm_order',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'mall.confirm_order',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
    'not_cache' => '1',
  ),
  'mall.my_visit' => 
  array (
    'url' => 'mall.my_visit',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.my_visit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.my_collect' => 
  array (
    'url' => 'mall.my_collect',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.my_collect',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.buyer_comment' => 
  array (
    'url' => 'mall.buyer_comment',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.buyer_comment',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.receiver' => 
  array (
    'url' => 'mall.receiver',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.receiver',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.receiver_add' => 
  array (
    'url' => 'mall.receiver_add',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.receiver_add',
    'bottom' => '',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.receiver_edit' => 
  array (
    'url' => 'mall.receiver_edit',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.receiver_edit',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.pay' => 
  array (
    'url' => 'mall.pay',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'mall.pay',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '1',
    'not_cache' => '1',
  ),
  'mall.goods_snapshot' => 
  array (
    'url' => 'mall.goods_snapshot',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'mall.goods_snapshot',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.auto_print' => 
  array (
    'url' => 'mall.auto_print',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.auto_print',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.my_order_detail' => 
  array (
    'url' => 'mall.my_order_detail',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.my_order_detail',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.checkout' => 
  array (
    'url' => 'mall.checkout',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.checkout',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.checkout_search' => 
  array (
    'url' => 'mall.checkout_search',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.checkout_search',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.checkout_print' => 
  array (
    'url' => 'mall.checkout_print',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.checkout_print',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.checkout_pay' => 
  array (
    'url' => 'mall.checkout_pay',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.checkout_pay',
    'bottom' => '',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'mall.scale' => 
  array (
    'url' => 'mall.scale',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.scale',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.scale_tag_print' => 
  array (
    'url' => 'mall.scale_tag_print',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.scale_tag_print',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.checkout_admin' => 
  array (
    'url' => 'mall.checkout_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.checkout_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.checkout_user' => 
  array (
    'url' => 'mall.checkout_user',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.checkout_user',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.checkout_order' => 
  array (
    'url' => 'mall.checkout_order',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.checkout_order',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.checkout_detail' => 
  array (
    'url' => 'mall.checkout_detail',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.checkout_detail',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.my_checkout_log' => 
  array (
    'url' => 'mall.my_checkout_log',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.my_checkout_log',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'mall.catalog' => 
  array (
    'url' => 'mall.catalog',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'mall.catalog',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'mall.edit_page_layout' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.edit_page_layout',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.edit_page_layout',
  ),
  'mall.edit_page_layout_add_module' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.edit_page_layout_add_module',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.edit_page_layout_add_module',
  ),
  'mall.edit_page_layout_view_module' => 
  array (
    'layout' => 'full',
    'head' => ',mall.layout',
    'left' => '',
    'right' => '',
    'full' => '',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.edit_page_layout_view_module',
  ),
  'mall.shop_foot' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.shop_foot',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.shop_foot',
  ),
  'mall.template' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.template',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.template',
  ),
  'mall.menu_set' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.menu_set',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.menu_set',
  ),
  'mall.diymodule_add' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.diymodule_add',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.diymodule_add',
  ),
  'mall.diypage_admin' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.diypage_admin',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.diypage_admin',
  ),
  'mall.diypage_add' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.diypage_add',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.diypage_add',
  ),
  'mall.diypage_edit' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.diypage_edit',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.diypage_edit',
  ),
  'mall.diypage_show' => 
  array (
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_122,mall.shop_name,mall.shop_search,mall.cart,mall.layout',
    'left' => '',
    'right' => '',
    'full' => '',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '0',
    'url' => 'mall.diypage_show',
  ),
  'mall.s_express' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.s_express',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.s_express',
  ),
  'mall.slider' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.slider',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.slider',
  ),
  'mall.slider_img' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.slider_img',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.slider_img',
  ),
  'mall.slider_show' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.slider_show',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.slider_show',
  ),
  'mall.replace_file' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.replace_file',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.replace_file',
  ),
  'mall.type_set' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.type_set',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.type_set',
  ),
  'mall.tag_set' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.tag_set',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.tag_set',
  ),
  'mall.s_tag_set' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.s_tag_set',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.s_tag_set',
  ),
  'mall.s_type_set' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.s_type_set',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.s_type_set',
  ),
  'mall.s_shop_type_set' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.s_shop_type_set',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.s_shop_type_set',
  ),
  'mall.talk' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.talk',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.talk',
  ),
  'mall.order_set' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.order_set',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.order_set',
  ),
  'mall.order_cancel' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.order_cancel',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.order_cancel',
  ),
  'mall.apply_refund' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.apply_refund',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.apply_refund',
  ),
  'mall.order_cancel_seller' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.order_cancel_seller',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.order_cancel_seller',
  ),
  'mall.view_refund' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.view_refund',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.view_refund',
  ),
  'mall.refund_express_voucher' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.refund_express_voucher',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.refund_express_voucher',
  ),
  'mall.view_refund_express' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.view_refund_express',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.view_refund_express',
  ),
  'mall.m_view_refund' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.m_view_refund',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.m_view_refund',
  ),
  'mall.finance' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.finance',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.finance',
  ),
  'mall.shop_finance' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.shop_finance',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.shop_finance',
  ),
  'mall.annual_fees' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.annual_fees',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.annual_fees',
  ),
  'mall.agent_admin' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.agent_admin',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.agent_admin',
  ),
  'mall.my_agent' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.my_agent',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.my_agent',
  ),
  'mall.agent_finance' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.agent_finance',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.agent_finance',
  ),
  'mall.bidding' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.bidding',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.bidding',
  ),
  'mall.bidding_detail' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.bidding_detail',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.bidding_detail',
  ),
  'mall.my_bidding_detail' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.my_bidding_detail',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.my_bidding_detail',
  ),
  'mall.my_bidding' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.my_bidding',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.my_bidding',
  ),
  'mall.turnover' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.turnover',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.turnover',
  ),
  'mall.my_buyer' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.my_buyer',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.my_buyer',
  ),
  'mall.deposit' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.deposit',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.deposit',
  ),
  'mall.group_set' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.group_set',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.group_set',
  ),
  'mall.buyer_group' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.buyer_group',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.buyer_group',
  ),
  'mall.coupon' => 
  array (
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_122,mall.shop_name,mall.shop_search,mall.cart,mall.layout',
    'left' => '',
    'right' => '',
    'full' => '',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'mall.coupon',
  ),
  'mall.coupon_usable' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.coupon_usable',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.coupon_usable',
  ),
  'mall.privilege' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.privilege',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.privilege',
  ),
  'mall.recommendation' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.recommendation',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.recommendation',
  ),
  'mall.recommendation_gain' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.recommendation_gain',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.recommendation_gain',
  ),
  'mall.recommendation_set' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.recommendation_set',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.recommendation_set',
  ),
  'mall.recommendation_log' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.recommendation_log',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.recommendation_log',
  ),
  'mall.recommendation_admin' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.recommendation_admin',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.recommendation_admin',
  ),
  'mall.coupon_push' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.coupon_push',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.coupon_push',
  ),
  'mall.coupon_log' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.coupon_log',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.coupon_log',
  ),
  'mall.search' => 
  array (
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'mall.search',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'mall.search',
  ),
  'mall.buy_coupon' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.buy_coupon',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.buy_coupon',
  ),
  'mall.buy_coupon_list' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.buy_coupon_list',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.buy_coupon_list',
  ),
  'mall.group_discount' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.group_discount',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.group_discount',
  ),
  'mall.increase_user' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.increase_user',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.increase_user',
  ),
  'mall.user_recharge' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.user_recharge',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.user_recharge',
  ),
  'mall.money_transfer' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.money_transfer',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.money_transfer',
  ),
  'mall.credits' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.credits',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.credits',
  ),
  'mall.headquarters' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.headquarters',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.headquarters',
  ),
  'mall.goods_db_admin' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.goods_db_admin',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.goods_db_admin',
  ),
  'mall.receiving_mode' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.receiving_mode',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.receiving_mode',
  ),
  'mall.goods_db' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.goods_db',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.goods_db',
  ),
  'mall.branch' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.branch',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.branch',
  ),
  'mall.branch_stock' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.branch_stock',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.branch_stock',
  ),
  'mall.branch_finance' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.branch_finance',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.branch_finance',
  ),
  'mall.branch_order' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.branch_order',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.branch_order',
  ),
  'mall.stocktake' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.stocktake',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.stocktake',
  ),
  'mall.stock' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.stock',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.stock',
  ),
  'mall.purchase' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.purchase',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.purchase',
  ),
  'mall.loss' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.loss',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.loss',
  ),
  'mall.deduct_stock' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.deduct_stock',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.deduct_stock',
  ),
  'mall.shelf_life' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.shelf_life',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.shelf_life',
  ),
  'mall.headquarters_index' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.headquarters_index',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.headquarters_index',
  ),
  'mall.batch_add_goods' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.batch_add_goods',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.batch_add_goods',
  ),
  'mall.h_goods_add' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.h_goods_add',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.h_goods_add',
  ),
  'mall.h_goods_add_option_type' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.h_goods_add_option_type',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.h_goods_add_option_type',
  ),
  'mall.h_goods_edit' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.h_goods_edit',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.h_goods_edit',
  ),
  'mall.stocktake_add' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.stocktake_add',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.stocktake_add',
  ),
  'mall.purchase_add' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.purchase_add',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.purchase_add',
  ),
  'mall.loss_add' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.loss_add',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.loss_add',
  ),
  'mall.deduct_stock_add' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.deduct_stock_add',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.deduct_stock_add',
  ),
  'mall.stocktake_list' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.stocktake_list',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.stocktake_list',
  ),
  'mall.branch_stock_detail' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.branch_stock_detail',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.branch_stock_detail',
  ),
  'mall.branch_order_list' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.branch_order_list',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.branch_order_list',
  ),
  'mall.branch_finance_list' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.branch_finance_list',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.branch_finance_list',
  ),
  'mall.shop_barpay' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.shop_barpay',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.shop_barpay',
  ),
  'mall.shop_tag' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.shop_tag',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.shop_tag',
  ),
  'mall.shop_tag_set' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.shop_tag_set',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.shop_tag_set',
  ),
  'mall.recharge' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.recharge',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.recharge',
  ),
  'mall.shelf_label' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.shelf_label',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.shelf_label',
  ),
  'mall.express_layout' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.express_layout',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.express_layout',
  ),
  'mall.express_consignor' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.express_consignor',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.express_consignor',
  ),
  'mall.express_print' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.express_print',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.express_print',
  ),
  'mall.create_card' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.create_card',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.create_card',
  ),
  'mall.span_shop' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.span_shop',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.span_shop',
  ),
  'mall.goods_in_out' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.goods_in_out',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.goods_in_out',
  ),
  'mall.storekeeper' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.storekeeper',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.storekeeper',
  ),
  'mall.create_card_list' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.create_card_list',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.create_card_list',
  ),
  'mall.create_card_detail' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.create_card_detail',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.create_card_detail',
  ),
  'mall.interest_index' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.interest_index',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.interest_index',
  ),
  'mall.interest_user' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.interest_user',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.interest_user',
  ),
  'mall.interest_group' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.interest_group',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.interest_group',
  ),
  'mall.interest_word' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.interest_word',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.interest_word',
  ),
  'mall.interest_word_grop' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.interest_word_grop',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.interest_word_grop',
  ),
  'mall.interest_user_list' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.interest_user_list',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.interest_user_list',
  ),
  'mall.interest_user_detail' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.interest_user_detail',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.interest_user_detail',
  ),
  'mall.interest_goods_list' => 
  array (
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'mall.interest_goods_list',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'mall.interest_goods_list',
    'not_cache' => '1',
  ),
  'mall.batch_reset_price' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.batch_reset_price',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.batch_reset_price',
  ),
  'mall.my_recommend' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.my_recommend',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.my_recommend',
  ),
  'mall.reg_recommend_goods' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.reg_recommend_goods',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.reg_recommend_goods',
  ),
  'mall.recommend_gain' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.recommend_gain',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.recommend_gain',
  ),
  'mall.my_recommend_gain' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.my_recommend_gain',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.my_recommend_gain',
  ),
  'mall.order_print_list' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.order_print_list',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.order_print_list',
  ),
  'mall.shop_map' => 
  array (
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'mall.shop_map',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'mall.shop_map',
  ),
  'mall.refund' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.refund',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.refund',
  ),
  'mall.refund_log' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.refund_log',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.refund_log',
  ),
  'mall.shop_module_set' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.shop_module_set',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.shop_module_set',
  ),
  'mall.touch_checkout' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.touch_checkout',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.touch_checkout',
  ),
  'mall.touch_checkout_search' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.touch_checkout_search',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.touch_checkout_search',
  ),
  'mall.phone_checkout_search' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.phone_checkout_search',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.phone_checkout_search',
  ),
  'mall.phone_checkout' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.phone_checkout',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.phone_checkout',
  ),
  'mall.checkout_index' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.checkout_index',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.checkout_index',
  ),
  'mall.brand_admin' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.brand_admin',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.brand_admin',
  ),
  'mall.brand_module_set' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.brand_module_set',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.brand_module_set',
  ),
  'mall.goods_get' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.goods_get',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.goods_get',
  ),
  'mall.public_stock' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.public_stock',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.public_stock',
  ),
  'mall.add_type_option' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.add_type_option',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'mall.add_type_option',
  ),
  'mall.online_forbid' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.online_forbid',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'mall.online_forbid',
  ),
  'mall.print_bar_code' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.print_bar_code',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.print_bar_code',
  ),
  'mall.credit_admin' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.credit_admin',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.credit_admin',
  ),
  'mall.goods_label' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.goods_label',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'mall.goods_label',
  ),
  'mall.quick_goods' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.quick_goods',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.quick_goods',
  ),
  'mall.check_code' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.check_code',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.check_code',
  ),
  'mall.type_goods' => 
  array (
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,mall.search,mall.cart,index.navigation,index.customer_service',
    'left' => '',
    'right' => '',
    'full' => 'mall.type_goods',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'mall.type_goods',
  ),
  'mall.reconciliation' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.reconciliation',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.reconciliation',
  ),
  'mall.reconciliation_log' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.reconciliation_log',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.reconciliation_log',
  ),
  'mall.storehouse' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'mall.storehouse',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.storehouse',
  ),
  'mall.stocking_order' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.stocking_order',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.stocking_order',
  ),
  'mall.stocking_order_edit' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.stocking_order_edit',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.stocking_order_edit',
  ),
  'mall.purchase_print' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'mall.purchase_print',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.purchase_print',
  ),
  'mall.id_increase_user' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.id_increase_user',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'mall.id_increase_user',
  ),
  'mall.gbuy_goods' => 
  array (
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_122,mall.shop_name,mall.shop_search,mall.cart,,mall.layout',
    'left' => '',
    'right' => '',
    'full' => 'mall.gbuy_goods(relevance_package_div:3|relevance_goods_div:2|goods_detail_div:1)',
    'bottom' => ',diypage.foot_six_grid,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'mall.gbuy_goods',
  ),
  'mall.gbuy_confirm_order' => 
  array (
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'mall.gbuy_confirm_order',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'mall.gbuy_confirm_order',
  ),
  'mall.hop_recharge_credits' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'mall.hop_recharge_credits',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'mall.hop_recharge_credits',
  ),
)?>