<?php return array (
  'ci.show_type' => 
  array (
    'url' => 'ci.show_type',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'ci.show_type',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'ci.list' => 
  array (
    'url' => 'ci.list',
    'layout' => 'right',
    'head' => 'index.top_bar,diymodule.show_121,ci.search,mall.cart,index.navigation,index.visitor_position',
    'left' => 'ci.show_type_module(id:0|width:100%|sub_width:50%|follow_type:true|quantity:100|height:100%|target:_self)',
    'right' => 'ci.list',
    'full' => 'ci.list',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'ci.detail' => 
  array (
    'url' => 'ci.detail',
    'layout' => 'left',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => 'ci.detail',
    'right' => 'ci.list_module(title:<span>R</span>相关推荐|id:0|follow_type:true|follow_page:true|tag:|quantity:10|sequence_field:sequence|sequence_type:desc|follow_type:true|follow_page:true|field:icon/title/reflash|target:_self|img:|img_link:|img_width:250px|width:100%|height:auto|i_width:100%)',
    'full' => '',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'ci.add_option_type' => 
  array (
    'url' => 'ci.add_option_type',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'ci.add_option_type',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'ci.add' => 
  array (
    'url' => 'ci.add',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'ci.add',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'ci.edit' => 
  array (
    'url' => 'ci.edit',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'ci.edit',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'ci.my_info' => 
  array (
    'url' => 'ci.my_info',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'ci.my_info',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'ci.admin' => 
  array (
    'url' => 'ci.admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'ci.admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'ci.info_admin' => 
  array (
    'url' => 'ci.info_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'ci.info_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'ci.type' => 
  array (
    'url' => 'ci.type',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'ci.type',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'ci.type_attribute' => 
  array (
    'url' => 'ci.type_attribute',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'ci.type_attribute',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'ci.type_attribute_add' => 
  array (
    'url' => 'ci.type_attribute_add',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'ci.type_attribute_add',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'ci.type_attribute_edit' => 
  array (
    'url' => 'ci.type_attribute_edit',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'ci.type_attribute_edit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'ci.type_remark' => 
  array (
    'url' => 'ci.type_remark',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'ci.type_remark',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'ci.type_price' => 
  array (
    'url' => 'ci.type_price',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'ci.type_price',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'ci.show_type_module_set' => 
  array (
    'url' => 'ci.show_type_module_set',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'ci.show_type_module_set',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'ci.list_module_set' => 
  array (
    'url' => 'ci.list_module_set',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'ci.list_module_set',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'ci.tag' => 
  array (
    'url' => 'ci.tag',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'ci.tag',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'ci.config' => 
  array (
    'url' => 'ci.config',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'ci.config',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'ci.search_log' => 
  array (
    'url' => 'ci.search_log',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'ci.search_log',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'ci.alias' => 
  array (
    'url' => 'ci.alias',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'ci.alias',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'ci.type_list_show' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'ci.type_list_show',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'ci.type_list_show',
  ),
  'ci.set_type' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'ci.set_type',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'ci.set_type',
  ),
  'ci.set_tag' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'ci.set_tag',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'ci.set_tag',
  ),
  'ci.reflash' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'ci.reflash',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'ci.reflash',
  ),
  'ci.top' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'ci.top',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'ci.top',
  ),
  'ci.newest' => 
  array (
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,ci.search,diymodule.show_119,index.navigation',
    'left' => '',
    'right' => '',
    'full' => 'ci.type_module_two,slider.show_16,diymodule.show_114,ci.list_module(module_diy:index_zf|title:<span>租</span>整租房|id:23|follow_type:true|follow_page:true|tag:|quantity:4|sequence_field:sequence|sequence_type:desc|follow_type:true|follow_page:true|field:icon/title/price/reflash/6/7/10|target:_self|img:|img_link:|img_width:250px|width:24%|height:460px|i_width:100%),ci.list_module(module_diy:|title:<span>售</span>二手房|id:27|follow_type:true|follow_page:true|tag:|quantity:5|sequence_field:id|sequence_type:desc|follow_type:true|follow_page:true|field:icon/title/reflash|target:_self|img:|img_link:|img_width:250px|width:24%|height:460px|i_width:100%),ci.list_module(module_diy:|title:<span>聘</span>找工作|id:138|follow_type:true|follow_page:true|tag:|quantity:5|sequence_field:sequence|sequence_type:desc|follow_type:true|follow_page:true|field:title/reflash/1810|target:_self|img:|img_link:|img_width:250px|width:24%|height:460px|i_width:100%),ci.list_module(module_diy:|title:<span>二</span>闲物转让|id:3|follow_type:true|follow_page:true|tag:|quantity:5|sequence_field:id|sequence_type:desc|follow_type:true|follow_page:true|field:icon/title/reflash|target:_self|img:|img_link:|img_width:250px|width:24%|height:460px|i_width:100%),diymodule.show_115,ci.list_module(module_diy:|title:<span>情</span>同城交友|id:10|follow_type:true|follow_page:true|tag:|quantity:4|sequence_field:sequence|sequence_type:desc|follow_type:true|follow_page:true|field:icon/title/reflash|target:_self|img:|img_link:|img_width:250px|width:24%|height:460px|i_width:100%),ci.list_module(module_diy:|title:<span>行</span>车辆买卖与服务|id:6|follow_type:true|follow_page:true|tag:|quantity:4|sequence_field:sequence|sequence_type:desc|follow_type:true|follow_page:true|field:icon/title/reflash|target:_self|img:|img_link:|img_width:250px|width:24%|height:460px|i_width:100%),ci.list_module(module_diy:|title:<span>家</span>生活服务|id:16|follow_type:true|follow_page:true|tag:|quantity:4|sequence_field:sequence|sequence_type:desc|follow_type:true|follow_page:true|field:icon/title/reflash|target:_self|img:|img_link:|img_width:250px|width:24%|height:460px|i_width:100%),ci.list_module(module_diy:|title:<span>公</span>商务服务|id:17|follow_type:true|follow_page:true|tag:|quantity:4|sequence_field:sequence|sequence_type:desc|follow_type:true|follow_page:true|field:icon/title/reflash|target:_self|img:|img_link:|img_width:250px|width:24%|height:460px|i_width:100%),diymodule.show_116,ci.list_module(module_diy:|title:<span>乐</span>宠物|id:7|follow_type:true|follow_page:true|tag:|quantity:4|sequence_field:sequence|sequence_type:desc|follow_type:true|follow_page:true|field:icon/title/reflash|target:_self|img:|img_link:|img_width:250px|width:24%|height:460px|i_width:100%),ci.list_module(module_diy:|title:<span>学</span>教育培训|id:18|follow_type:true|follow_page:true|tag:|quantity:4|sequence_field:sequence|sequence_type:desc|follow_type:true|follow_page:true|field:icon/title/reflash|target:_self|img:|img_link:|img_width:250px|width:24%|height:460px|i_width:100%),ci.list_module(module_diy:|title:<span>玩</span>旅游酒店|id:19|follow_type:true|follow_page:true|tag:|quantity:4|sequence_field:sequence|sequence_type:desc|follow_type:true|follow_page:true|field:icon/title/reflash|target:_self|img:|img_link:|img_width:250px|width:24%|height:460px|i_width:100%),ci.list_module(module_diy:|title:<span>新</span>最近发布|id:0|follow_type:true|follow_page:true|tag:|quantity:4|sequence_field:id|sequence_type:desc|follow_type:true|follow_page:true|field:icon/title/reflash|target:_self|img:|img_link:|img_width:250px|width:24%|height:460px|i_width:100%),diymodule.show_117',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'ci.newest',
  ),
  'ci.search' => 
  array (
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'ci.search',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'ci.search',
  ),
)?>