<?php return array (
  'index.index' => 
  array (
    'url' => 'index.index',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,mall.search,mall.cart,index.navigation,slider.show_15,mall.type_module_two,index.fixed_top',
    'left' => '',
    'right' => '',
    'full' => 'index.index_user,mall.interest_goods,mall.shop_module(store_tag:|width:100%|height:auto|module_diy:|circle:0|sequence_field:sequence|sequence_type:desc|quantity:16|target:_blank|title:商家联盟),mall.goods_module(id:9|field:normal_price/multi_angle_img|tag:|store_tag:|width:100%|height:auto|first:0|module_diy:index_1f|show_sold_satisfaction:0|sequence_field:bidding_show|sequence_type:desc|quantity:8|show_method:show_grid|target:_self|pc_buy_button:0|phone_buy_button:1|title:<span>1F</span> 数码产品|show_sub:3|img:2018_05/28/1527485147_0_5686*png|img_link:|img_width:18rem|follow_type:false|follow_page:false|scroll:no),diymodule.show_114,mall.goods_module(id:1|field:unit/multi_angle_img|tag:|store_tag:|width:100%|height:auto|first:0|module_diy:index_2f|show_sold_satisfaction:0|sequence_field:bidding_show|sequence_type:desc|quantity:8|show_method:show_grid|target:_blank|pc_buy_button:1|phone_buy_button:1|title:<SPAN>2F</span>女装|show_sub:3|img:2018_05/28/1527485198_0_4278*png|img_link:|img_width:18rem|follow_type:false|follow_page:false|scroll:null),diymodule.show_115,mall.goods_module(id:6|field:unit|tag:|store_tag:|width:100%|height:auto|first:0|module_diy:index_3f|show_sold_satisfaction:0|sequence_field:bidding_show|sequence_type:desc|quantity:8|show_method:show_grid|target:_blank|pc_buy_button:0|phone_buy_button:1|title:<span>3F</span>童装童鞋玩具|show_sub:3|img:2018_07/09/1531118371_0_7377*png|img_link:|img_width:18rem|follow_type:false|follow_page:false|scroll:null),mall.goods_module(id:0|field:|tag:|store_tag:|width:100%|height:auto|first:0|module_diy:index_4f|show_sold_satisfaction:0|sequence_field:id|sequence_type:desc|quantity:8|show_method:show_grid|target:_blank|pc_buy_button:0|phone_buy_button:1|title:<SPAN>4F</span> 新货上架|show_sub:3|img:2018_05/28/1527485331_0_5401*png|img_link:|img_width:18rem|follow_type:false|follow_page:false|scroll:null)',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'index.edit_page_layout' => 
  array (
    'url' => 'index.edit_page_layout',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => 'index.edit_page_layout',
    'full' => 'index.edit_page_layout',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.edit_page_layout_add_module' => 
  array (
    'url' => 'index.edit_page_layout_add_module',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'index.edit_page_layout_add_module',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.edit_page_layout_view_module' => 
  array (
    'url' => 'index.edit_page_layout_view_module',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'index.top_bar,index.head,index.foot,index.navigation,index.customer_service,,,,slider.show_4,slider.show_5,slider.show_6,,',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.set_module_data_quantity' => 
  array (
    'url' => 'index.set_module_data_quantity',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'index.set_module_data_quantity',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.install' => 
  array (
    'url' => 'index.install',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.install',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.edit_user' => 
  array (
    'url' => 'index.edit_user',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.edit_user',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.edit_user&field=password' => 
  array (
    'url' => 'index.edit_user&field=password',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.edit_user',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.edit_user&field=transaction_password' => 
  array (
    'url' => 'index.edit_user&field=transaction_password',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.edit_user',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.group_require_info' => 
  array (
    'url' => 'index.group_require_info',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.group_require_info',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.reg_user' => 
  array (
    'url' => 'index.reg_user',
    'layout' => 'full',
    'head' => 'diymodule.show_134,index.reg_user',
    'left' => '',
    'right' => '',
    'full' => '',
    'bottom' => 'index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.resetPassword' => 
  array (
    'url' => 'index.resetPassword',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'index.resetPassword',
    'bottom' => 'index.foot,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.user' => 
  array (
    'url' => 'index.user',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position',
    'left' => 'index.user',
    'right' => 'index.user,mall.buyer,',
    'full' => 'mall.master_sum,index.sum,index.user_sum,mall.buyer_sum,ci.user_sum',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'index.login' => 
  array (
    'url' => 'index.login',
    'layout' => 'full',
    'head' => 'diymodule.show_134,index.login',
    'left' => '',
    'right' => '',
    'full' => '',
    'bottom' => 'index.foot,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '1',
    'not_cache' => '1',
  ),
  'index.admin_group' => 
  array (
    'url' => 'index.admin_group',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.admin_group',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.admin_navigation' => 
  array (
    'url' => 'index.admin_navigation',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.admin_navigation',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.replace_file' => 
  array (
    'url' => 'index.replace_file',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'index.replace_file',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.admin_edit_user' => 
  array (
    'url' => 'index.admin_edit_user',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.admin_edit_user',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.admin_users' => 
  array (
    'url' => 'index.admin_users',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.admin_users',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.view_menu' => 
  array (
    'url' => 'index.view_menu',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.view_menu,',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.edit_menu' => 
  array (
    'url' => 'index.edit_menu',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.edit_menu,',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.view_page' => 
  array (
    'url' => 'index.view_page',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.view_page',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.edit_page' => 
  array (
    'url' => 'index.edit_page',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.edit_page,',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.view_function' => 
  array (
    'url' => 'index.view_function',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.view_function',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.edit_function' => 
  array (
    'url' => 'index.edit_function',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.edit_function,',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.edit_group_parent' => 
  array (
    'url' => 'index.edit_group_parent',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.edit_group_parent',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.edit_user_group' => 
  array (
    'url' => 'index.edit_user_group',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.edit_user_group',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.login_log' => 
  array (
    'url' => 'index.login_log',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.login_log',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.phone_msg' => 
  array (
    'url' => 'index.phone_msg',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.phone_msg',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.email_msg' => 
  array (
    'url' => 'index.email_msg',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.email_msg',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.site_msg' => 
  array (
    'url' => 'index.site_msg',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.site_msg',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.site_msg_sender' => 
  array (
    'url' => 'index.site_msg_sender',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.site_msg_sender',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.site_msg_addressee' => 
  array (
    'url' => 'index.site_msg_addressee',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.site_msg_addressee',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.site_msg_detail' => 
  array (
    'url' => 'index.site_msg_detail',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.site_msg_detail',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.email_msg_sender' => 
  array (
    'url' => 'index.email_msg_sender',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.email_msg_sender',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.phone_msg_sender' => 
  array (
    'url' => 'index.phone_msg_sender',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.phone_msg_sender',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.email_msg_detail' => 
  array (
    'url' => 'index.email_msg_detail',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.email_msg_detail',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.admin_msg' => 
  array (
    'url' => 'index.admin_msg',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.admin_msg',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.admin_site_msg' => 
  array (
    'url' => 'index.admin_site_msg',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.admin_site_msg',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.admin_email_msg' => 
  array (
    'url' => 'index.admin_email_msg',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.admin_email_msg',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.admin_phone_msg' => 
  array (
    'url' => 'index.admin_phone_msg',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.admin_phone_msg',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.admin_site_msg_detail' => 
  array (
    'url' => 'index.admin_site_msg_detail',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.admin_site_msg_detail',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.admin_email_msg_detail' => 
  array (
    'url' => 'index.admin_email_msg_detail',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.admin_email_msg_detail',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.admin_smtp' => 
  array (
    'url' => 'index.admin_smtp',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.admin_smtp',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.config' => 
  array (
    'url' => 'index.config',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.config',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.program_config' => 
  array (
    'url' => 'index.program_config',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.program_config',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.language_list' => 
  array (
    'url' => 'index.language_list',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.language_list',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.language_edit' => 
  array (
    'url' => 'index.language_edit',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.language_edit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.closed' => 
  array (
    'url' => 'index.closed',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'index.closed',
    'bottom' => 'index.foot,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.payment' => 
  array (
    'url' => 'index.payment',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.payment',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.recharge' => 
  array (
    'url' => 'index.recharge',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.recharge',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.withdraw' => 
  array (
    'url' => 'index.withdraw',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.withdraw',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.financial_center' => 
  array (
    'url' => 'index.financial_center',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.financial_center',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.financial_center_admin' => 
  array (
    'url' => 'index.financial_center_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.financial_center_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.withdraw_log_admin' => 
  array (
    'url' => 'index.withdraw_log_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.withdraw_log_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.recharge_log_admin' => 
  array (
    'url' => 'index.recharge_log_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.recharge_log_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.money_log_admin' => 
  array (
    'url' => 'index.money_log_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.money_log_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.withdraw_log' => 
  array (
    'url' => 'index.withdraw_log',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.withdraw_log',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.recharge_log' => 
  array (
    'url' => 'index.recharge_log',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.recharge_log',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.money_log' => 
  array (
    'url' => 'index.money_log',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.money_log',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.money_transfer' => 
  array (
    'url' => 'index.money_transfer',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.money_transfer',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.money_transfer_log' => 
  array (
    'url' => 'index.money_transfer_log',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.money_transfer_log',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.money_transfer_log_admin' => 
  array (
    'url' => 'index.money_transfer_log_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.money_transfer_log_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.program_upgrade' => 
  array (
    'url' => 'index.program_upgrade',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.program_upgrade',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.template_admin' => 
  array (
    'url' => 'index.template_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.template_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.template_upgrade' => 
  array (
    'url' => 'index.template_upgrade',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.template_upgrade',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.template_edit' => 
  array (
    'url' => 'index.template_edit',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.template_edit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.template_edit_file' => 
  array (
    'url' => 'index.template_edit_file',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'index.template_edit_file',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.template_replace_file' => 
  array (
    'url' => 'index.template_replace_file',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'index.template_replace_file',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.head_edit' => 
  array (
    'url' => 'index.head_edit',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.head_edit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.diy_phone_home_page_edit' => 
  array (
    'url' => 'index.diy_phone_home_page_edit',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.diy_phone_home_page_edit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.foot_edit' => 
  array (
    'url' => 'index.foot_edit',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.foot_edit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.robot' => 
  array (
    'url' => 'index.robot',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'index.robot',
    'bottom' => '',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.not_found' => 
  array (
    'url' => 'index.not_found',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'index.not_found',
    'bottom' => '',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'index.db' => 
  array (
    'url' => 'index.db',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.db',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.img_set' => 
  array (
    'url' => 'index.img_set',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.img_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.user_set' => 
  array (
    'url' => 'index.user_set',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.user_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.user_set_item' => 
  array (
    'url' => 'index.user_set_item',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.user_set_item',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.customer_service_set' => 
  array (
    'url' => 'index.customer_service_set',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.customer_service_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.area_set' => 
  array (
    'url' => 'index.area_set',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.area_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.personal_center' => 
  array (
    'url' => 'index.personal_center',
    'layout' => 'full',
    'head' => 'index.user_position,index.admin_nv',
    'left' => '',
    'right' => '',
    'full' => 'index.personal_center',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.public_content_sttings' => 
  array (
    'url' => 'index.public_content_sttings',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.public_content_sttings',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.mass_msg' => 
  array (
    'url' => 'index.mass_msg',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.mass_msg',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.program_backup' => 
  array (
    'url' => 'index.program_backup',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.program_backup',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.program_recovery' => 
  array (
    'url' => 'index.program_recovery',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.program_recovery',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.debug_fix' => 
  array (
    'url' => 'index.debug_fix',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.debug_fix',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'index.test' => 
  array (
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => ',slider.show_4',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'index.test',
  ),
  'index.oauth_bind_option' => 
  array (
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'index.oauth_bind_option',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'index.oauth_bind_option',
  ),
  'index.oauth' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.oauth',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.oauth',
  ),
  'index.edit_phone' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.edit_phone',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.edit_phone',
  ),
  'index.edit_email' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.edit_email',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.edit_email',
  ),
  'index.my_oauth' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.my_oauth',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.my_oauth',
  ),
  'index.map' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.map',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.map',
  ),
  'index.right_buttons' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.right_buttons',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'index.right_buttons',
  ),
  'index.increase_user' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.increase_user',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.increase_user',
  ),
  'index.user_recharge' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.user_recharge',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.user_recharge',
  ),
  'index.sum_set' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.sum_set',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.sum_set',
  ),
  'index.phone_bottom_set' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.phone_bottom_set',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.phone_bottom_set',
  ),
  'index.credits_log' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.credits_log',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.credits_log',
  ),
  'index.credits_admin' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.credits_admin',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.credits_admin',
  ),
  'index.safe' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.safe',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'index.safe',
  ),
  'index.openid' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'index.openid',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.openid',
  ),
  'index.safe_question_admin' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.safe_question_admin',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.safe_question_admin',
  ),
  'index.safe_question_set' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.safe_question_set',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.safe_question_set',
  ),
  'index.safe_question' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'index.safe_question',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.safe_question',
  ),
  'index.circle_set' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.circle_set',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'index.circle_set',
  ),
  'index.circle' => 
  array (
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,mall.search,mall.cart,index.navigation,index.customer_service',
    'left' => '',
    'right' => '',
    'full' => 'index.circle',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'index.circle',
  ),
  'index.color' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'index.color',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'index.color',
  ),
  'index.color_edit' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.color_edit',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'index.color_edit',
  ),
  'index.user_debit' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.user_debit',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.user_debit',
  ),
  'index.user_map' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.user_map',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'index.user_map',
  ),
  'index.wxpay' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.wxpay',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.wxpay',
  ),
  'index.send_wxmoney' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.send_wxmoney',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.send_wxmoney',
  ),
  'index.my_recommend_qr' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.my_recommend_qr',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.my_recommend_qr',
  ),
  'index.my_new_user' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.my_new_user',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.my_new_user',
  ),
  'index.share' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.share',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'index.share',
  ),
  'index.my_user_qr' => 
  array (
    'layout' => 'full',
    'head' => 'index.user_position,index.admin_nv',
    'left' => '',
    'right' => '',
    'full' => 'index.my_user_qr',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.my_user_qr',
  ),
  'index.my_pay_qr' => 
  array (
    'layout' => 'full',
    'head' => 'index.user_position,index.admin_nv',
    'left' => '',
    'right' => '',
    'full' => 'index.my_pay_qr',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.my_pay_qr',
  ),
  'index.api_index' => 
  array (
    'layout' => 'full',
    'head' => 'index.user_position,index.admin_nv',
    'left' => '',
    'right' => '',
    'full' => 'index.api_index',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.api_index',
  ),
  'index.api_user' => 
  array (
    'layout' => 'full',
    'head' => 'index.user_position,index.admin_nv',
    'left' => '',
    'right' => '',
    'full' => 'index.api_user',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.api_user',
  ),
  'index.api_log' => 
  array (
    'layout' => 'full',
    'head' => 'index.user_position,index.admin_nv',
    'left' => '',
    'right' => '',
    'full' => 'index.api_log',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.api_log',
  ),
  'index.api_my' => 
  array (
    'layout' => 'full',
    'head' => 'index.user_position,index.admin_nv',
    'left' => '',
    'right' => '',
    'full' => 'index.api_my',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.api_my',
  ),
  'index.api_list' => 
  array (
    'layout' => 'full',
    'head' => 'index.user_position,index.admin_nv',
    'left' => '',
    'right' => '',
    'full' => 'index.api_list',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.api_list',
  ),
  'index.truncate' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.truncate',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'index.truncate',
  ),
  'index.id_increase_user' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.id_increase_user',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.id_increase_user',
  ),
  'index.authorize_code' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'index.authorize_code',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'index.authorize_code',
  ),
  'index.quick_button' => 
  array (
    'layout' => 'full',
    'head' => 'index.user_position,index.admin_nv',
    'left' => '',
    'right' => '',
    'full' => 'index.quick_button',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'index.quick_button',
  ),
  'index.user_field' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.user_field',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.user_field',
  ),
  'index.index_user_set' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.index_user_set',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '0',
    'url' => 'index.index_user_set',
  ),
  'index.user_debit_credits' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.user_debit_credits',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.user_debit_credits',
  ),
  'index.user_recharge_credits' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.user_recharge_credits',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.user_recharge_credits',
  ),
  'index.recharge_credits' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.recharge_credits',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.recharge_credits',
  ),
  'index.shop_recharge_credits' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.shop_recharge_credits',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.shop_recharge_credits',
  ),
  'index.credits_transfer' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'index.credits_transfer',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'index.credits_transfer',
  ),
)?>