<?php return array (
  'form.power' => 
  array (
    'url' => 'form.power',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'form.power',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'form.data_add' => 
  array (
    'url' => 'form.data_add',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'diymodule.show_126,form.data_add',
    'bottom' => '',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'form.data_show_list' => 
  array (
    'url' => 'form.data_show_list',
    'layout' => 'full',
    'head' => 'index.head,index.navigation,index.visitor_position,',
    'left' => '',
    'right' => '',
    'full' => 'form.data_show_list',
    'bottom' => 'diypage.foot_six_grid,index.device,index.customer_service',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'form.data_show_detail' => 
  array (
    'url' => 'form.data_show_detail',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.navigation,index.visitor_position,',
    'left' => '',
    'right' => '',
    'full' => 'form.data_show_detail',
    'bottom' => 'diypage.foot_six_grid,index.device,index.customer_service',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'form.data_admin' => 
  array (
    'url' => 'form.data_admin',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'form.data_admin',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'form.data_edit' => 
  array (
    'url' => 'form.data_edit',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'form.data_edit',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'form.table_admin' => 
  array (
    'url' => 'form.table_admin',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'form.table_admin',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'form.table_add' => 
  array (
    'url' => 'form.table_add',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'form.table_add',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'form.table_edit' => 
  array (
    'url' => 'form.table_edit',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'form.table_edit',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'form.field_add' => 
  array (
    'url' => 'form.field_add',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'form.field_add',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'form.field_edit' => 
  array (
    'url' => 'form.field_edit',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'form.field_edit',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'form.table_css' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'form.table_css',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'form.table_css',
  ),
)?>