<?php return array (
  'program' => 
  array (
    'language' => 'chinese_simplified',
    'cache_time' => 5,
    'template_1' => 'default',
    'template_0' => 'default',
    'imageMark' => false,
    'state' => 'opening',
    'thumb_width' => '512',
    'thumb_height' => '512',
  ),
  'class_name' => 'distribution',
  'version' => '3.0',
  'compatible_template_version' => '3.0',
  'author' => 'Monxin',
  'author_url' => 'http://www.monxin.com',
  'program_unlogin_function_power' => 
  array (
    0 => 'distribution.index',
  ),
  'dashboard_module' => 
  array (
    0 => 'distribution.user_sum',
    1 => 'distribution.master_sum',
  ),
  'task_y' => '2018',
  'task_m' => '2018-08',
  'task_d' => '2018-08-29',
  'task_h' => '2016-01-03 19',
  'task_minute' => '2016-01-03 19:11',
  'receive_task_y' => '2018',
  'receive_task_m' => '2018-08',
  'receive_task_d' => '2018-08-28',
  'receive_task_h' => '2016-01-03 20',
  'receive_task_minute' => '2016-01-03 20:34',
  'check' => 0,
  'level' => 3,
  'level_1' => 0,
  'level_2' => 0,
  'level_3' => 0,
  'level_4' => '0',
  'level_5' => '0',
  'level_6' => '0',
  'level_7' => '0',
  'level_8' => '0',
  'level_9' => '0',
  'shop_rate' => 0,
  'all_order' => 1,
)?>