<?php return array (
  'distribution.index' => 
  array (
    'url' => 'distribution.index',
    'layout' => 'full',
    'head' => 'distribution.index,',
    'left' => '',
    'right' => '',
    'full' => 'mall.type_goods',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'distribution.master' => 
  array (
    'url' => 'distribution.master',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'distribution.master',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'distribution.config' => 
  array (
    'url' => 'distribution.config',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'distribution.config',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'distribution.order_admin' => 
  array (
    'url' => 'distribution.order_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'distribution.order_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'distribution.distributor' => 
  array (
    'url' => 'distribution.distributor',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'distribution.distributor',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'distribution.my_distributor' => 
  array (
    'url' => 'distribution.my_distributor',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'distribution.my_distributor',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'distribution.apply' => 
  array (
    'url' => 'distribution.apply',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'distribution.apply',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'distribution.order' => 
  array (
    'url' => 'distribution.order',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'distribution.order',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'distribution.user' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'distribution.user',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'distribution.user',
  ),
  'distribution.qr' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'distribution.qr',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'distribution.qr',
  ),
  'distribution.show_sub' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'distribution.show_sub',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'distribution.show_sub',
  ),
)?>