<?php return array (
  'bargain.admin' => 
  array (
    'url' => 'bargain.admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'bargain.admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'bargain.config' => 
  array (
    'url' => 'bargain.config',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'bargain.config',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'bargain.goods_admin' => 
  array (
    'url' => 'bargain.goods_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'bargain.goods_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'bargain.order_admin' => 
  array (
    'url' => 'bargain.order_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'bargain.order_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'bargain.shop' => 
  array (
    'url' => 'bargain.shop',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'bargain.shop',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'bargain.goods' => 
  array (
    'url' => 'bargain.goods',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'bargain.goods',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'bargain.order' => 
  array (
    'url' => 'bargain.order',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'bargain.order',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'bargain.my' => 
  array (
    'url' => 'bargain.my',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'bargain.my',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'bargain.goods_set' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'bargain.goods_set',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'bargain.goods_set',
  ),
  'bargain.list' => 
  array (
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'bargain.list',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'bargain.list',
  ),
  'bargain.detail' => 
  array (
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'bargain.detail,mall.goods_module(id:0|field:|tag:|store_tag:|width:100%|height:auto|first:0|module_diy:|show_sold_satisfaction:0|sequence_field:sequence|sequence_type:desc|quantity:10|show_method:show_grid|target:_self|pc_buy_button:1|phone_buy_button:0|title:推荐商品|show_sub:0|img:|img_link:|img_width:250px|follow_type:true|follow_page:true|scroll:null)',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'bargain.detail',
  ),
  'bargain.goods_view' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'bargain.goods_view',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'bargain.goods_view',
  ),
  'bargain.log_detail' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'bargain.log_detail',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'bargain.log_detail',
  ),
  'bargain.bargaing' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'bargain.bargaing',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'bargain.bargaing',
  ),
  'bargain.bargaing_admin' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'bargain.bargaing_admin',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'bargain.bargaing_admin',
  ),
)?>