<?php return array (
  'pk.show' => 
  array (
    'url' => 'pk.show',
    'layout' => 'full',
    'head' => 'index.top_bar,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'pk.show',
    'bottom' => 'index.foot,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'pk.admin' => 
  array (
    'url' => 'pk.admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'pk.admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'pk.style' => 
  array (
    'url' => 'pk.style',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'pk.style',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'pk.my' => 
  array (
    'url' => 'pk.my',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'pk.my',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'pk.item' => 
  array (
    'url' => 'pk.item',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'pk.item',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'pk.object' => 
  array (
    'url' => 'pk.object',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'pk.object',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'pk.value' => 
  array (
    'url' => 'pk.value',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'pk.value',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
)?>