<?php return array (
  'copy.regular' => 
  array (
    'url' => 'copy.regular',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'copy.regular',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'copy.regular_add' => 
  array (
    'url' => 'copy.regular_add',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'copy.regular_add',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'copy.regular_edit' => 
  array (
    'url' => 'copy.regular_edit',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'copy.regular_edit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'copy.table' => 
  array (
    'url' => 'copy.table',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'copy.table',
    'bottom' => 'index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'copy.field' => 
  array (
    'url' => 'copy.field',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'copy.field',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'copy.task_list' => 
  array (
    'url' => 'copy.task_list',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'copy.task_list',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'copy.file_list' => 
  array (
    'url' => 'copy.file_list',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'copy.file_list',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'copy.task' => 
  array (
    'url' => 'copy.task',
    'layout' => 'full',
    'head' => 'index.top_bar',
    'left' => '',
    'right' => '',
    'full' => '',
    'bottom' => 'copy.task,index.foot,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'copy.file' => 
  array (
    'url' => 'copy.file',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'copy.file',
    'bottom' => 'index.foot,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '1',
  ),
)?>