<?php 
return array(
	'article.index'=>array(
		'edit_url'=>'',
		'pagesize'=>'',
		'share'=>false,
	),
	'article.type'=>array(
		'edit_url'=>'',
		'pagesize'=>'10',
		'share'=>false,
	),
	'article.add'=>array(
		'edit_url'=>'',
		'pagesize'=>'',
		'share'=>false,
	),
	'article.admin'=>array(
		'edit_url'=>'',
		'pagesize'=>'10',
		'share'=>false,
	),
	'article.edit'=>array(
		'edit_url'=>'',
		'pagesize'=>'',
		'share'=>false,
	),
	'article.show(field:title/tag/time/visit/src/content)'=>array(
		'edit_url'=>'index.php?monxin=article.edit&id=',
		'pagesize'=>'',
		'share'=>false,
	),
	'article.show_article_list(field:title/src|target:_self|sequence_field:sequence|sequence_type:desc|quantity:10|sub_module_width:280px|content_length:100|follow_type:true|follow_page:true)'=>array(
		'edit_url'=>'index.php?monxin=article.admin&type',
		'pagesize'=>'',
		'share'=>false,
	),
	'article.show_article_list_set'=>array(
		'edit_url'=>'',
		'pagesize'=>'',
		'share'=>false,
	),
				'article.show_list(id:0|field:title|sequence_field:sequence|sequence_type:desc|quantity:10|width:100%|height:auto|target:_self|title:|scroll:top|sub_module_width:280px|content_length:100|follow_type:true|follow_page:true)'=>array(
		'edit_url'=>'index.php?monxin=article.admin&type=',
		'pagesize'=>'',
		'share'=>true,
	),
	'article.show_list_set'=>array(
		'edit_url'=>'',
		'pagesize'=>'',
		'share'=>false,
	),
	'article.show_type(id:0|title:diy_name|show_deep:3|width:100%|height:auto|target:_self|follow_type:true)'=>array(
		'edit_url'=>'index.php?monxin=article.type&id=',
		'pagesize'=>'',
		'share'=>true,
	),
	'article.show_type_set'=>array(
		'edit_url'=>'',
		'pagesize'=>'',
		'share'=>false,
	),
	'article.show_set'=>array(
		'edit_url'=>'',
		'pagesize'=>'',
		'share'=>false,
	),
);

?>