<?php return array (
  'article.index' => 
  array (
    'url' => 'article.index',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => 'article.index',
    'right' => '',
    'full' => 'article.index',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'article.type' => 
  array (
    'url' => 'article.type',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'article.type',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'article.add' => 
  array (
    'url' => 'article.add',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'article.add',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'article.admin' => 
  array (
    'url' => 'article.admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'article.admin',
    'bottom' => 'index.foot',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'article.edit' => 
  array (
    'url' => 'article.edit',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'article.edit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'article.show' => 
  array (
    'url' => 'article.show',
    'layout' => 'left',
    'head' => 'index.top_bar,diymodule.show_121,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => 'article.show(id:undefined|field:title/tag/visit/time/src/content)',
    'right' => 'article.show_type(id:0|width:100%|height:auto|show_deep:3|target:_self|title:diy_name|follow_type:true),article.show_list(id:0|field:title/src/content/visit/time|width:100%|height:auto|sequence_field:sequence|sequence_type:desc|quantity:10|target:_self|title:trew|scroll:up|sub_module_width:97%|content_length:20|follow_type:true|follow_page:true)',
    'full' => 'article.show(id:undefined|field:title/tag/visit/time/src/content)',
    'bottom' => 'index.foot,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'article.show_list_set' => 
  array (
    'url' => 'article.show_list_set',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'article.show_list_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'article.show_article_list_set' => 
  array (
    'url' => 'article.show_article_list_set',
    'layout' => 'full',
    'head' => 'index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'article.show_article_list_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'article.show_type_set' => 
  array (
    'url' => 'article.show_type_set',
    'layout' => 'full',
    'head' => 'index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'article.show_type_set',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'article.show_set' => 
  array (
    'url' => 'article.show_set',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'article.show_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'article.show_article_list' => 
  array (
    'url' => 'article.show_article_list',
    'layout' => 'right',
    'head' => 'index.top_bar,diymodule.show_121,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => 'article.show_type(id:0|width:100%|height:auto|show_deep:3|target:_self|title:diy_name11|follow_type:true),article.show_list(id:0|field:title|width:100%|height:auto|sequence_field:sequence|sequence_type:desc|quantity:10|target:_self|title:aerhj|scroll:null|sub_module_width:45%|content_length:100|follow_type:true|follow_page:true),',
    'right' => 'article.show_article_list(field:title/src/content/visit/time|sequence_field:sequence|sequence_type:desc|quantity:10|target:_self|sub_module_width:99%|content_length:100)',
    'full' => '',
    'bottom' => 'index.foot,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '1',
  ),
)?>