<?php return array (
  'weixin.index' => 
  array (
    'url' => 'weixin.index',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,diymodule.show_123,,,index.navigation,index.visitor_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.index',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.admin_index' => 
  array (
    'url' => 'weixin.admin_index',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.admin_index',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.account_add' => 
  array (
    'url' => 'weixin.account_add',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.account_add',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.account_edit' => 
  array (
    'url' => 'weixin.account_edit',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.account_edit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.account_list' => 
  array (
    'url' => 'weixin.account_list',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.account_list',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.account_admin' => 
  array (
    'url' => 'weixin.account_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.account_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.menu_list' => 
  array (
    'url' => 'weixin.menu_list',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.menu_list',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.auto_answer_list' => 
  array (
    'url' => 'weixin.auto_answer_list',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.auto_answer_list',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.auto_answer_add' => 
  array (
    'url' => 'weixin.auto_answer_add',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.auto_answer_add',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.auto_answer_edit' => 
  array (
    'url' => 'weixin.auto_answer_edit',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.auto_answer_edit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.function_list' => 
  array (
    'url' => 'weixin.function_list',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.function_list',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.function_edit' => 
  array (
    'url' => 'weixin.function_edit',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.function_edit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.search_function_add' => 
  array (
    'url' => 'weixin.search_function_add',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.search_function_add',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.search_function_edit' => 
  array (
    'url' => 'weixin.search_function_edit',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.search_function_edit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.search_function_list' => 
  array (
    'url' => 'weixin.search_function_list',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.search_function_list',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.dialog_list' => 
  array (
    'url' => 'weixin.dialog_list',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.dialog_list',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.dialog' => 
  array (
    'url' => 'weixin.dialog',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.send_msg,weixin.dialog',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.user_list' => 
  array (
    'url' => 'weixin.user_list',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.user_list',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.user_edit' => 
  array (
    'url' => 'weixin.user_edit',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.user_edit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'weixin.diy_qr' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.diy_qr',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'weixin.diy_qr',
  ),
  'weixin.mass' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'weixin.mass',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '0',
    'url' => 'weixin.mass',
  ),
)?>