<?php 
return array(
	'image.index'=>array(
		'edit_url'=>'',
		'pagesize'=>'',
		'share'=>false,
	),
	'image.type'=>array(
		'edit_url'=>'',
		'pagesize'=>'10',
		'share'=>false,
	),
	'image.type_remark'=>array(
		'edit_url'=>'',
		'pagesize'=>'',
		'share'=>false,
	),
	'image.add'=>array(
		'edit_url'=>'',
		'pagesize'=>'',
		'share'=>false,
	),
	'image.admin'=>array(
		'edit_url'=>'',
		'pagesize'=>'10',
		'share'=>false,
	),
	'image.edit'=>array(
		'edit_url'=>'',
		'pagesize'=>'',
		'share'=>false,
	),
	'image.show'=>array(
		'edit_url'=>'index.php?monxin=image.edit&id=',
		'pagesize'=>'',
		'share'=>false,
	),
	'image.product'=>array(
		'edit_url'=>'index.php?monxin=image.edit&id=',
		'pagesize'=>'',
		'share'=>false,
	),
	'image.show_thumb(field:title/src|target:_self|detail_show_method:show|sequence_field:sequence|sequence_type:desc|quantity:10|sub_module_width:280px|image_height:256px)'=>array(
		'edit_url'=>'index.php?monxin=image.admin&id=',
		'pagesize'=>'',
		'share'=>false,
	),
	'image.show_thumb_set'=>array(
		'edit_url'=>'',
		'pagesize'=>'',
		'share'=>false,
	),
					'image.show_list(id:0|field:title/src|detail_show_method:show|sequence_field:sequence|sequence_type:desc|quantity:10|width:100%|height:auto|target:_self|title:diy_name|scroll:no|sub_module_width:280px|image_height:256px|follow_type:true|follow_page:true)'=>array(
		'edit_url'=>'index.php?monxin=image.admin&type=',
		'pagesize'=>'',
		'share'=>true,
	),
	'image.show_list_set'=>array(
		'edit_url'=>'',
		'pagesize'=>'',
		'share'=>false,
	),
	'image.show_type(id:0|title:diy_name|show_deep:3|width:100%|height:auto|target:_self|follow_type:true)'=>array(
		'edit_url'=>'index.php?monxin=image.type&id=',
		'pagesize'=>'',
		'share'=>true,
	),
	'image.show_type_set'=>array(
		'edit_url'=>'',
		'pagesize'=>'',
		'share'=>false,
	),
	
					'image.type_module(id:0|field:title/src|sequence_field:sequence|sequence_type:desc|quantity:10|width:100%|height:auto|target:_self|title:diy_name|scroll:no|sub_module_width:280px|image_height:256px|follow_type:true)'=>array(
		'edit_url'=>'index.php?monxin=image.type',
		'pagesize'=>'',
		'share'=>true,
	),
	'image.type_module_set'=>array(
		'edit_url'=>'',
		'pagesize'=>'',
		'share'=>false,
	),
	'image.type_list'=>array(
		'edit_url'=>'index.php?monxin=image.type',
		'pagesize'=>10,
		'share'=>false,
	),
	
);

?>