<?php return array (
  'image.index' => 
  array (
    'url' => 'image.index',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => 'image.index',
    'full' => 'image.index',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'image.type' => 
  array (
    'url' => 'image.type',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'image.type',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'image.type_remark' => 
  array (
    'url' => 'image.type_remark',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'image.type_remark',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'image.add' => 
  array (
    'url' => 'image.add',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'image.add',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'image.admin' => 
  array (
    'url' => 'image.admin',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'image.admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'image.edit' => 
  array (
    'url' => 'image.edit',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'image.edit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'image.show' => 
  array (
    'url' => 'image.show',
    'layout' => 'full',
    'head' => ',index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'image.show',
    'bottom' => '',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'image.show_content_set' => 
  array (
    'url' => 'image.show_content_set',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'image.show_content_set',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'image.show_list_set' => 
  array (
    'url' => 'image.show_list_set',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'image.show_list_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'image.show_thumb_set' => 
  array (
    'url' => 'image.show_thumb_set',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'image.show_thumb_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'image.show_type_set' => 
  array (
    'url' => 'image.show_type_set',
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.user_position',
    'left' => '',
    'right' => '',
    'full' => 'image.show_type_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'image.show_thumb' => 
  array (
    'url' => 'image.show_thumb',
    'layout' => 'right',
    'head' => 'index.top_bar,diymodule.show_121,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => 'image.show_type(id:0|title:diy_name|show_deep:3|width:100%|height:auto|target:_self|follow_type:true),',
    'right' => 'image.show_thumb(field:title/src|sequence_field:id|sequence_type:desc|quantity:8|target:_blank|sub_module_width:21%|image_height:11rem|detail_show_method:show)',
    'full' => '',
    'bottom' => 'index.foot,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'image.type_module_set' => 
  array (
    'layout' => 'full',
    'head' => 'index.top_bar,index.head,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'image.type_module_set',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '1',
    'require_login' => '1',
    'url' => 'image.type_module_set',
  ),
  'image.type_list' => 
  array (
    'layout' => 'full',
    'head' => 'index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'image.type_list',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'image.type_list',
  ),
  'image.product' => 
  array (
    'layout' => 'right',
    'head' => 'index.top_bar,diymodule.show_121,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => 'image.show_type(id:0|title:diy_name|show_deep:3|width:100%|height:auto|target:_self|follow_type:true)',
    'right' => 'image.product',
    'full' => '',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'image.product',
  ),
)?>