<?php return array (
  'gbuy.master' => 
  array (
    'url' => 'gbuy.master',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'gbuy.master',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'gbuy.config' => 
  array (
    'url' => 'gbuy.config',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'gbuy.config',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'gbuy.goods' => 
  array (
    'url' => 'gbuy.goods',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'gbuy.goods',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'gbuy.group' => 
  array (
    'url' => 'gbuy.group',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'gbuy.group',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'gbuy.shop' => 
  array (
    'url' => 'gbuy.shop',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'gbuy.shop',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'gbuy.shop_group' => 
  array (
    'url' => 'gbuy.shop_group',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'gbuy.shop_group',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'gbuy.shop_goods' => 
  array (
    'url' => 'gbuy.shop_goods',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'gbuy.shop_goods',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'gbuy.buyer' => 
  array (
    'url' => 'gbuy.buyer',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'gbuy.buyer',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'gbuy.my_group' => 
  array (
    'url' => 'gbuy.my_group',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'gbuy.my_group',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'gbuy.my_buy' => 
  array (
    'url' => 'gbuy.my_buy',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'gbuy.my_buy',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'gbuy.list' => 
  array (
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'gbuy.list',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'gbuy.list',
  ),
  'gbuy.detail' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'gbuy.detail,mall.goods_module(id:0|field:|tag:|store_tag:|width:100%|height:auto|first:0|module_diy:|show_sold_satisfaction:0|sequence_field:sequence|sequence_type:desc|quantity:10|show_method:show_grid|target:_self|pc_buy_button:1|phone_buy_button:0|title:推荐商品|show_sub:0|img:|img_link:|img_width:250px|follow_type:true|follow_page:true|scroll:null)',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'gbuy.detail',
  ),
  'gbuy.goods_set' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'gbuy.goods_set',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'gbuy.goods_set',
  ),
  'gbuy.goods_view' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'gbuy.goods_view',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '1',
    'url' => 'gbuy.goods_view',
  ),
  'gbuy.pay' => 
  array (
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'gbuy.pay',
    'bottom' => '',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'gbuy.pay',
  ),
  'gbuy.order' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'gbuy.order',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'gbuy.order',
  ),
  'gbuy.shop_order' => 
  array (
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'gbuy.shop_order',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'gbuy.shop_order',
  ),
)?>