<?php return array (
  'diypage.index' => 
  array (
    'url' => 'diypage.index',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => 'diypage.index',
    'right' => '',
    'full' => 'diypage.index',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'diypage.type' => 
  array (
    'url' => 'diypage.type',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'diypage.type',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'diypage.add' => 
  array (
    'url' => 'diypage.add',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'diypage.add',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'diypage.admin' => 
  array (
    'url' => 'diypage.admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'diypage.admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'diypage.edit' => 
  array (
    'url' => 'diypage.edit',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'diypage.edit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'diypage.show' => 
  array (
    'url' => 'diypage.show',
    'layout' => 'right',
    'head' => 'index.top_bar,diymodule.show_121,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => 'diypage.show_list(id:0|field:title|width:100%|height:auto|sequence_field:sequence|sequence_type:desc|quantity:10|target:_self|title:三生荟|scroll:no|sub_module_width:100%)',
    'right' => 'diypage.show(id:undefined|field:title/content)',
    'full' => '',
    'bottom' => 'diypage.foot_six_grid,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'diypage.show_content_set' => 
  array (
    'url' => 'diypage.show_content_set',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'diypage.show_content_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'diypage.show_list_set' => 
  array (
    'url' => 'diypage.show_list_set',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'diypage.show_list_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'diypage.show_type_set' => 
  array (
    'url' => 'diypage.show_type_set',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'diypage.show_type_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'diypage.show_set' => 
  array (
    'url' => 'diypage.show_set',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'diypage.show_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'diypage.show_page_list' => 
  array (
    'url' => 'diypage.show_page_list',
    'layout' => 'right',
    'head' => 'index.top_bar,diymodule.show_121,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => 'diypage.show_type(id:0|width:100%|height:auto|show_deep:3|target:_self|title:分类导航)',
    'right' => 'diypage.show_page_list(field:title/visit/time|sequence_field:sequence|sequence_type:desc|quantity:10|target:_self|sub_module_width:100%|image_height:100px)',
    'full' => ',diypage.show_page_list(field:title/visit/time|sequence_field:sequence|sequence_type:desc|quantity:10|target:_self|sub_module_width:100%|image_height:100px)',
    'bottom' => 'index.foot,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'diypage.show_page_list_set' => 
  array (
    'url' => 'diypage.show_page_list_set',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'diypage.show_page_list_set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'diypage.foot_six_grid_set' => 
  array (
    'url' => 'diypage.foot_six_grid_set',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'diypage.foot_six_grid_set,diypage.foot_six_grid',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'diypage.app' => 
  array (
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,mall.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'diymodule.show_149',
    'bottom' => 'index.foot,index.device',
    'target' => '_self',
    'tutorial' => '0',
    'require_login' => '0',
    'url' => 'diypage.app',
  ),
)?>