<?php return array (
  'im.talk' => 
  array (
    'url' => 'im.talk',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'im.talk',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'im.index' => 
  array (
    'url' => 'im.index',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'im.index',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'im.msg' => 
  array (
    'url' => 'im.msg',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'im.msg',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'im.talk_admin' => 
  array (
    'url' => 'im.talk_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'im.talk_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'im.talk_log' => 
  array (
    'url' => 'im.talk_log',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'im.talk_log',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'im.forbidden' => 
  array (
    'url' => 'im.forbidden',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'im.forbidden',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'im.set' => 
  array (
    'url' => 'im.set',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'im.set',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'im.sender' => 
  array (
    'url' => 'im.sender',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'im.sender',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
)?>