<?php return array (
  'scanpay.master' => 
  array (
    'url' => 'scanpay.master',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'scanpay.master',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'scanpay.account_admin' => 
  array (
    'url' => 'scanpay.account_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'scanpay.account_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'scanpay.pay_admin' => 
  array (
    'url' => 'scanpay.pay_admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'scanpay.pay_admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'scanpay.payee' => 
  array (
    'url' => 'scanpay.payee',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'scanpay.payee',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'scanpay.my_account' => 
  array (
    'url' => 'scanpay.my_account',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'scanpay.my_account',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'scanpay.account_add' => 
  array (
    'url' => 'scanpay.account_add',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'scanpay.account_add',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'scanpay.account_edit' => 
  array (
    'url' => 'scanpay.account_edit',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'scanpay.account_edit',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'scanpay.account_pay_log' => 
  array (
    'url' => 'scanpay.account_pay_log',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'scanpay.account_pay_log',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'scanpay.pay' => 
  array (
    'url' => 'scanpay.pay',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'scanpay.pay',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'scanpay.operator_log' => 
  array (
    'url' => 'scanpay.operator_log',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'scanpay.operator_log',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
)?>