<?php return array (
  'credit.use' => 
  array (
    'url' => 'credit.use',
    'layout' => 'full',
    'head' => 'index.top_bar,diymodule.show_121,ci.search,mall.cart,index.navigation,index.visitor_position',
    'left' => '',
    'right' => '',
    'full' => 'credit.use',
    'bottom' => 'index.foot,index.device',
    'require_login' => '0',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'credit.my_use' => 
  array (
    'url' => 'credit.my_use',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'credit.my_use',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'credit.index' => 
  array (
    'url' => 'credit.index',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'credit.index',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'credit.user' => 
  array (
    'url' => 'credit.user',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'credit.user',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'credit.increase' => 
  array (
    'url' => 'credit.increase',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'credit.increase',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'credit.decrease' => 
  array (
    'url' => 'credit.decrease',
    'layout' => 'full',
    'head' => '',
    'left' => '',
    'right' => '',
    'full' => 'credit.decrease',
    'bottom' => '',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '0',
  ),
  'credit.admin' => 
  array (
    'url' => 'credit.admin',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'credit.admin',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'credit.prize' => 
  array (
    'url' => 'credit.prize',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'credit.prize',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
  'credit.prize_log' => 
  array (
    'url' => 'credit.prize_log',
    'layout' => 'full',
    'head' => 'index.admin_nv,index.user_position,',
    'left' => '',
    'right' => '',
    'full' => 'credit.prize_log',
    'bottom' => 'index.foot,index.device',
    'require_login' => '1',
    'target' => '_self',
    'tutorial' => '1',
  ),
)?>